# Generated by Django 2.0.5 on 2018-08-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='python', max_length=100, unique=True),
        ),
    ]
