# Generated by Django 2.0.5 on 2018-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
