# Generated by Django 2.0.5 on 2018-08-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180818_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='level',
            field=models.CharField(default='intermediate', max_length=100),
        ),
    ]
